/**
 * @description Content constants for the Replit Templates Gallery replica.
 */

export const REPLIT_CONTENT = {
  categories: [
    { id: "all", name: "All Templates", icon: "LayoutGrid" },
    { id: "web", name: "Web Development", icon: "Globe" },
    { id: "data", name: "Data Science", icon: "BarChart3" },
    { id: "game", name: "Game Development", icon: "Gamepad2" },
    { id: "ai", name: "AI & ML", icon: "Brain" },
    { id: "mobile", name: "Mobile", icon: "Smartphone" },
  ],
  templates: [
    {
      id: 1,
      title: "Next.js",
      author: "replit",
      description: "A Next.js template with TypeScript and Tailwind CSS.",
      category: "web",
      language: "TypeScript",
      runs: "1.2M",
      tags: ["React", "Framework"],
      color: "#000000",
    },
    {
      id: 2,
      title: "Python",
      author: "replit",
      description: "The classic Python environment for scripts and data.",
      category: "data",
      language: "Python",
      runs: "5.4M",
      tags: ["Beginner", "Scripting"],
      color: "#3776AB",
    },
    {
      id: 3,
      title: "Node.js",
      author: "replit",
      description: "Build scalable network applications with JavaScript.",
      category: "web",
      language: "JavaScript",
      runs: "2.1M",
      tags: ["Backend", "Server"],
      color: "#339933",
    },
    {
      id: 4,
      title: "Pygame",
      author: "replit",
      description: "Create 2D games with the popular Python library.",
      category: "game",
      language: "Python",
      runs: "800K",
      tags: ["Game", "Graphics"],
      color: "#FFD43B",
    },
    {
      id: 5,
      title: "Flask",
      author: "replit",
      description: "A lightweight WSGI web application framework.",
      category: "web",
      language: "Python",
      runs: "950K",
      tags: ["Web", "API"],
      color: "#000000",
    },
    {
      id: 6,
      title: "C++",
      author: "replit",
      description: "High-performance systems programming environment.",
      category: "all",
      language: "C++",
      runs: "1.5M",
      tags: ["Systems", "Performance"],
      color: "#00599C",
    },
    {
      id: 7,
      title: "TensorFlow",
      author: "replit",
      description: "Machine learning and deep learning with TensorFlow.",
      category: "ai",
      language: "Python",
      runs: "400K",
      tags: ["AI", "ML"],
      color: "#FF6F00",
    },
    {
      id: 8,
      title: "React Native",
      author: "replit",
      description: "Build native mobile apps using React.",
      category: "mobile",
      language: "JavaScript",
      runs: "300K",
      tags: ["Mobile", "Cross-platform"],
      color: "#61DAFB",
    }
  ],
  sidebarLinks: [
    { name: "Home", icon: "Home" },
    { name: "Templates", icon: "Layout" },
    { name: "My Repls", icon: "Folder" },
    { name: "Community", icon: "Users" },
    { name: "Teams", icon: "Shield" },
  ]
};
